* Spacemacs setup

This repo contains =.spacemacs= and the private config layers for
Spacemacs. These files are meant to be symlinked from their expected
locations (ie, the home directory for =.spacemacs= and
=.emacs.d/private= for the private config layers). See
[[https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org][the
Spacemacs documentation]] for details about managing an external repo of
config layers.

*Note:* Another option aside from symlinking is setting the
=dotspacemacs-configuration-layer-path= variable in =.spacemacs=, but I
haven't tried it yet.

** Private config layer: Work

The =work= directory contains a config layer with its own =packages.el=
and =extensions.el=. It's currently configured for Rails development.

*** Setup

1. Create a symlink for =work= in =.emacs.d/private=.

Example: =ln -sv dotfiles/work=

2. Add =work= to the list of config layers in =.spacemacs=.

Example: =(setq-default dotspacemacs-configuration-layers '(work))=

3. Spacemacs will automatically download and install any new packages
   after startup. Make sure to define a =work/init-<package>= function
   for each package in =packages.el=. If there are no customizations to
   be made, simply calling =(use-package <package>)= within the function
   is enough. (See
   [[https://github.com/jwiegley/use-package][use-package]] for more
   details on usage.)

Example:

=(defun work/init-haml-mode ()      (use-package haml-mode))=

** Org mode

I found out that
[[https://github.com/railwaycat/emacs-mac-port/][emacs-mac-port]], which
ports Emacs 24.5, contains the latest stable version of Org, which is
8.2.10 as of October 2014 according to the Org main page. However, it
still doesn't contain the =contrib= packages, so I'll leave the
instructions for manual installation here.

As for Spacemacs, the current version I've got installed (0.101.5,
commit 94d6b65) has spun out Org into its own layer, so I've added =org=
to the list of layers in =.spacemacs=.

*** Manual installation

The =org-8.2.10= directory is currently located in the =work= private
config layer. In the future it could be moved into its own private
config layer for modularity.

To install a new version of Org:

1. Download the latest stable release from
   [[http://orgmode.org/][Orgmode.org]] and unpack it into a private
   config layer.

2. Add the =org-x.x.xx/lisp= directory to the load path in =.spacemacs=:

Example:
=(add-to-list 'load-path "~/.emacs.d/private/work/org-8.2.10/lisp")=

*** Contribution packages

1. To load Org contributions, add the =org-x.x.xx/contrib/lisp=
   directory to the load path in =.spacemacs=:

Example:
=(add-to-list 'load-path "~/.emacs.d/private/work/org-8.2.10/contrib/lisp")=

2. Packages in =contrib= apparently aren't loaded by default; they have
   to be required in =.spacemacs=:

Example: =(require 'ox-s5)=

*** Checking the Org version

=M-x org-version= will display the version of Org, as well as the
installation path for more recent versions. See the
[[http://orgmode.org/worg/org-faq.html#orgheadline21][Org FAQ section on
mixed installations]] for possible errors related to manual
installation.

** .spacemacs

*** Setup

Create a symlink for =.spacemacs= in =/home/<user>=.

Note: For OS X, symlink =spacemacs-mac/.spacemacs=.

Example: =ln -sv dotfiles/.spacemacs=
